project-name: alxe.github.io
base-path: / # https://alxe.github.io/
context:
  static:
    site-title: My personal webpage
    personal-info:
      contact-email: alxegod@gmail.com
  dynamic:
    generated_on: datetime.now()